services:
  db:
    image: postgres:16.4-alpine
    container_name: j_app_db
    env_file: .env
    networks:
      - j-app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: ../infra/api.Dockerfile
    image: j-app-server:latest
    container_name: j_app_server
    depends_on:
      - db
    env_file: .env
    networks:
      - j-app-network
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: ../infra/web.Dockerfile
    image: j-app-web:latest
    container_name: j_app_web
    depends_on:
      - api
    links:
      - api
    env_file: .env
    networks:
      - j-app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: j_app_nginx
    depends_on:
      - web
      - api
    links:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
    networks:
      - j-app-network
    restart: unless-stopped

networks:
  j-app-network:
    name: j-app-network

volumes:
  db_data:
